# -*- coding: utf-8 -*-
# Deployment settings for c:\marmalade\7.4\web\wmApplication\target\wmApplication.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.4/s3e/makefile_builder/mkb.py', 'c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/Indian_Bollywood_Quiz.mkb', '--deploy-only', '--hub-data', 'C:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/project_Indian_Bollywood_Quiz/mkb-web.txt', '--buildenv=WEB', '--use-prebuilt']
mkb = 'c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/Indian_Bollywood_Quiz.mkb'
mkf = ['c:\\marmalade\\7.4\\web\\wmapplication\\wmapplication_prebuilt.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/data/webassets', 'webassets', 0),
    ('c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/data/iwaudiocapture', 'iwaudiocapture', 0),
]

assets['including_iwui_style'] = [
    ('c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/data/webassets', 'webassets', 0),
    ('c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/data/iwaudiocapture', 'iwaudiocapture', 0),
    ('c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/data/iwui_style', 'iwui_style', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Indian_Bollywood_Quiz'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Indian_Bollywood_Quiz'
    long_caption = 'Indian_Bollywood_Quiz'
    version = [0, 0, 1]
    config = ['c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/data/app.icf']
    data_dir = 'c:/Users/hchhabra/Documents/apps8/Indian_Bollywood_Quiz/data'
    iphone_link_lib = ['s3eWebView', 's3eDialog', 's3eNUI ', 's3eOverlay']
    osx_ext_dll = ['c:/marmalade/7.4/extensions/s3ewebview/lib/osx/libs3eWebView.dylib', 'c:/marmalade/7.4/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib', 'c:/marmalade/7.4/extensions/s3edialog/lib/osx/libs3eDialog.dylib', 'c:/marmalade/7.4/web/wmapplication/extensions/s3eoverlay/lib/osx/libs3eOverlay.dylib']
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/marmalade/7.4/extensions/s3ewebview/lib/win32/s3eWebView.dll', 'c:/marmalade/7.4/extensions/pvrtextool/lib/win32/PVRTexTool.dll', 'c:/marmalade/7.4/extensions/s3edialog/lib/win32/s3eDialog.dll', 'c:/marmalade/7.4/web/wmapplication/extensions/s3eoverlay/lib/win32/s3eOverlay.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['c:/marmalade/7.4/extensions/s3ewebview/lib/iphone', 'c:/marmalade/7.4/extensions/s3edialog/lib/iphone', 'c:/marmalade/7.4/extensions/s3enui/lib/iphone', 'c:/marmalade/7.4/web/wmapplication/extensions/s3eoverlay/lib/iphone']
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    ws8_extra_res = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = ['c:/marmalade/7.4/extensions/s3ewebview/lib/android/s3eWebView.jar', 'c:/marmalade/7.4/extensions/s3edialog/lib/android/s3eDialog.jar', 'c:/marmalade/7.4/extensions/s3enui/lib/android/s3eNUI.jar', 'c:/marmalade/7.4/extensions/s3eaudiocapture/lib/android/s3eAudioCapture.jar', 'c:/marmalade/7.4/web/wmapplication/extensions/s3eoverlay/lib/android/s3eOverlay.jar']
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_so = ['c:/marmalade/7.4/extensions/s3ewebview/lib/android/libs3eWebView.so', 'c:/marmalade/7.4/extensions/s3edialog/lib/android/libs3eDialog.so', 'c:/marmalade/7.4/extensions/s3enui/lib/android/libs3eNUI.so', 'c:/marmalade/7.4/extensions/s3eaudiocapture/lib/android/libs3eAudioCapture.so', 'c:/marmalade/7.4/web/wmapplication/extensions/s3eoverlay/lib/android/libs3eOverlay.so']
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.s86',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.js',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.s3e',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.so',
                 },
         'arm' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.s3e',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication_d.s86',
                   'release' : r'c:\marmalade\7.4\web\wmApplication\target\wmApplication.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()

######### Configuration: Windows

c = DeployConfig()
config['Windows'] = c
c.os = ['win32']
c.arch = ['x86']
c.target_folder = 'Windows'
c.assets = assets['including_iwui_style']

######### Configuration: Mac OS X

c = DeployConfig()
config['Mac OS X'] = c
c.os = ['osx']
c.arch = ['x86']
c.target_folder = 'Mac OS X'
c.assets = assets['including_iwui_style']
